FILES = [
  "echo_scrape/1950DA.txt",
  "echo_scrape/1992sk.txt",
  "echo_scrape/1994CCa.txt",
  "echo_scrape/1996hw1.txt",
  "echo_scrape/1998ky26.txt",
  "echo_scrape/1998ml14.txt",
  "echo_scrape/1998wt24.txt",
  "echo_scrape/1999kw4a.txt",
  "echo_scrape/1999kw4b.txt",
  "echo_scrape/2002ce26.txt",
  "echo_scrape/2008ev5.txt",
  "echo_scrape/bacchus.txt",
  "echo_scrape/betulia.txt",
  "echo_scrape/castalia.txt",
  "echo_scrape/geographos.txt",
  "echo_scrape/golevka.txt",
  "echo_scrape/itokawa.txt",
  "echo_scrape/mithra.txt",
  "echo_scrape/nereus.txt",
  "echo_scrape/rashalom.txt",
  "echo_scrape/toutatis.txt",
  "echo_scrape/yorp.txt",
  "damit_scrape/1980 TZ5.txt",
  "damit_scrape/1981 EE45.txt",
  "damit_scrape/1981 EO20.txt",
  "damit_scrape/1982 BJ13.txt",
  "damit_scrape/1989 AD.txt",
  "damit_scrape/1989 UT2.txt",
  "damit_scrape/1989 WD.txt",
  "damit_scrape/1990 EJ.txt",
  "damit_scrape/1990 FV.txt",
  "damit_scrape/1990 HW1.txt",
  "damit_scrape/1990 KB1.txt",
  "damit_scrape/1990 QN1.txt",
  "damit_scrape/1990 SB.txt",
  "damit_scrape/1990 SN6.txt",
  "damit_scrape/1990 TZ.txt",
  "damit_scrape/1990 WM.txt",
  "damit_scrape/1990 YM.txt",
  "damit_scrape/1991 AO2.txt",
  "damit_scrape/1991 PN10.txt",
  "damit_scrape/1991 RS13.txt",
  "damit_scrape/1991 YH.txt",
  "damit_scrape/1992 MJ.txt",
  "damit_scrape/1993 BW3.txt",
  "damit_scrape/1993 SK16.txt",
  "damit_scrape/1993 UF1.txt",
  "damit_scrape/1993 VM1.txt",
  "damit_scrape/1994 JD.txt",
  "damit_scrape/1994 WF2.txt",
  "damit_scrape/1994 WU2.txt",
  "damit_scrape/1995 DD2.txt",
  "damit_scrape/1995 VS1.txt",
  "damit_scrape/1995 YB1.txt",
  "damit_scrape/1996 AU3.txt",
  "damit_scrape/1996 HW1.txt",
  "damit_scrape/1996 TB6.txt",
  "damit_scrape/1997 AT1.txt",
  "damit_scrape/1997 FZ1.txt",
  "damit_scrape/1997 SV2.txt",
  "damit_scrape/1997 TD6.txt",
  "damit_scrape/1997 TZ7.txt",
  "damit_scrape/1997 WD21.txt",
  "damit_scrape/1998 BA44.txt",
  "damit_scrape/1998 BO12.txt",
  "damit_scrape/1998 FT115.txt",
  "damit_scrape/1998 FX62.txt",
  "damit_scrape/1998 GP2.txt",
  "damit_scrape/1998 HS36.txt",
  "damit_scrape/1998 KU48.txt",
  "damit_scrape/1998 QE4.txt",
  "damit_scrape/1998 QK93.txt",
  "damit_scrape/1998 QQ39.txt",
  "damit_scrape/1998 QY40.txt",
  "damit_scrape/1998 RD53.txt",
  "damit_scrape/1998 RL76.txt",
  "damit_scrape/1998 RS2.txt",
  "damit_scrape/1998 SK119.txt",
  "damit_scrape/1998 WS.txt",
  "damit_scrape/1998 XJ94.txt",
  "damit_scrape/1998 XK72.txt",
  "damit_scrape/1999 CK46.txt",
  "damit_scrape/1999 CM51.txt",
  "damit_scrape/1999 CM8.txt",
  "damit_scrape/1999 GB17.txt",
  "damit_scrape/1999 JH52.txt",
  "damit_scrape/1999 JV107.txt",
  "damit_scrape/1999 LH13.txt",
  "damit_scrape/1999 NC57.txt",
  "damit_scrape/1999 RB158.txt",
  "damit_scrape/1999 RN61.txt",
  "damit_scrape/1999 RT54.txt",
  "damit_scrape/1999 RU10.txt",
  "damit_scrape/1999 SR18.txt",
  "damit_scrape/1999 TG2.txt",
  "damit_scrape/1999 TK207.txt",
  "damit_scrape/1999 TX41.txt",
  "damit_scrape/1999 VF128.txt",
  "damit_scrape/1999 XB127.txt",
  "damit_scrape/1999 XE45.txt",
  "damit_scrape/1999 XK105.txt",
  "damit_scrape/1999 XL32.txt",
  "damit_scrape/1999 XM181.txt",
  "damit_scrape/1999 XP120.txt",
  "damit_scrape/2000 AC98.txt",
  "damit_scrape/2000 AF10.txt",
  "damit_scrape/2000 AK119.txt",
  "damit_scrape/2000 AQ58.txt",
  "damit_scrape/2000 AR97.txt",
  "damit_scrape/2000 AZ120.txt",
  "damit_scrape/2000 DR4.txt",
  "damit_scrape/2000 EV64.txt",
  "damit_scrape/2000 GE133.txt",
  "damit_scrape/2000 HH53.txt",
  "damit_scrape/2000 JA46.txt",
  "damit_scrape/2000 JM54.txt",
  "damit_scrape/2000 KQ58.txt",
  "damit_scrape/2000 ND17.txt",
  "damit_scrape/2000 NV9.txt",
  "damit_scrape/2000 PG26.txt",
  "damit_scrape/2000 QJ42.txt",
  "damit_scrape/2000 QV192.txt",
  "damit_scrape/2000 SD249.txt",
  "damit_scrape/2000 SR124.txt",
  "damit_scrape/2000 UO97.txt",
  "damit_scrape/2000 XK18.txt",
  "damit_scrape/2001 FU192.txt",
  "damit_scrape/2001 MA25.txt",
  "damit_scrape/2001 OZ11.txt",
  "damit_scrape/2001 PX5.txt",
  "damit_scrape/2001 QY78.txt",
  "damit_scrape/2001 RD84.txt",
  "damit_scrape/2001 RO19.txt",
  "damit_scrape/2001 VG45.txt",
  "damit_scrape/2001 XD3.txt",
  "damit_scrape/2001 XM167.txt",
  "damit_scrape/2002 AK1.txt",
  "damit_scrape/2002 AW61.txt",
  "damit_scrape/2002 JO1.txt",
  "damit_scrape/2002 QU40.txt",
  "damit_scrape/2003 EX2.txt",
  "damit_scrape/Abifraeman.txt",
  "damit_scrape/Academia.txt",
  "damit_scrape/Achaia.txt",
  "damit_scrape/Ada.txt",
  "damit_scrape/Adams.txt",
  "damit_scrape/Adele.txt",
  "damit_scrape/Adelheid.txt",
  "damit_scrape/Adrastea.txt",
  "damit_scrape/Aeternitas.txt",
  "damit_scrape/Aethra.txt",
  "damit_scrape/Afra.txt",
  "damit_scrape/Agnia.txt",
  "damit_scrape/Aguntina.txt",
  "damit_scrape/Aho.txt",
  "damit_scrape/Aisleen.txt",
  "damit_scrape/Aivazovskij.txt",
  "damit_scrape/Akagi.txt",
  "damit_scrape/Alexandra.txt",
  "damit_scrape/Alice.txt",
  "damit_scrape/Alkmene.txt",
  "damit_scrape/Alma.txt",
  "damit_scrape/Alphonsina.txt",
  "damit_scrape/Alstede.txt",
  "damit_scrape/Althaea.txt",
  "damit_scrape/Amalasuntha.txt",
  "damit_scrape/Amanda.txt",
  "damit_scrape/Amata.txt",
  "damit_scrape/Ambartsumian.txt",
  "damit_scrape/Ambrosia.txt",
  "damit_scrape/Amelia.txt",
  "damit_scrape/Amherstia.txt",
  "damit_scrape/Amicitia.txt",
  "damit_scrape/Amosov.txt",
  "damit_scrape/Amphitrite.txt",
  "damit_scrape/Amy.txt",
  "damit_scrape/Anahita.txt",
  "damit_scrape/Anatoliya.txt",
  "damit_scrape/Angelina.txt",
  "damit_scrape/Anna.txt",
  "damit_scrape/Annette.txt",
  "damit_scrape/Antigone.txt",
  "damit_scrape/Antonia.txt",
  "damit_scrape/Antwerpia.txt",
  "damit_scrape/Apollo.txt",
  "damit_scrape/Appenzella.txt",
  "damit_scrape/Ara.txt",
  "damit_scrape/Arabis.txt",
  "damit_scrape/Arachne.txt",
  "damit_scrape/Arduina.txt",
  "damit_scrape/Arethusa.txt",
  "damit_scrape/Argelander.txt",
  "damit_scrape/Ariadne.txt",
  "damit_scrape/Armisticia.txt",
  "damit_scrape/Arsinoe.txt",
  "damit_scrape/Aruna.txt",
  "damit_scrape/Aschera.txt",
  "damit_scrape/Ashizuri.txt",
  "damit_scrape/Aspasia.txt",
  "damit_scrape/Asplinda.txt",
  "damit_scrape/Asporina.txt",
  "damit_scrape/Asterope.txt",
  "damit_scrape/Astraea.txt",
  "damit_scrape/Atala.txt",
  "damit_scrape/Atalante.txt",
  "damit_scrape/Athamantis.txt",
  "damit_scrape/Athene.txt",
  "damit_scrape/Athor.txt",
  "damit_scrape/Atossa.txt",
  "damit_scrape/Augusta.txt",
  "damit_scrape/Auravictrix.txt",
  "damit_scrape/Aurelia.txt",
  "damit_scrape/Auricula.txt",
  "damit_scrape/Aurora.txt",
  "damit_scrape/Ausonia.txt",
  "damit_scrape/Austria.txt",
  "damit_scrape/Ayako.txt",
  "damit_scrape/Azalea.txt",
  "damit_scrape/Bach.txt",
  "damit_scrape/Backlunda.txt",
  "damit_scrape/Baedeker.txt",
  "damit_scrape/Bahner.txt",
  "damit_scrape/Bali.txt",
  "damit_scrape/Bambery.txt",
  "damit_scrape/Banachiewicza.txt",
  "damit_scrape/Barbarossa.txt",
  "damit_scrape/Barnardiana.txt",
  "damit_scrape/Barolo.txt",
  "damit_scrape/Barringer.txt",
  "damit_scrape/Barry.txt",
  "damit_scrape/Bathilde.txt",
  "damit_scrape/Bauschinger.txt",
  "damit_scrape/Bechuana.txt",
  "damit_scrape/Begonia.txt",
  "damit_scrape/Beijingdaxue.txt",
  "damit_scrape/Belisana.txt",
  "damit_scrape/Bella.txt",
  "damit_scrape/Bellona.txt",
  "damit_scrape/Berbericia.txt",
  "damit_scrape/Bernardina.txt",
  "damit_scrape/Bernardus.txt",
  "damit_scrape/Bertha.txt",
  "damit_scrape/Bettina.txt",
  "damit_scrape/Betulia.txt",
  "damit_scrape/Bezovec.txt",
  "damit_scrape/Bianca.txt",
  "damit_scrape/Bilbo.txt",
  "damit_scrape/Billpickering.txt",
  "damit_scrape/Bittesini.txt",
  "damit_scrape/Bodea.txt",
  "damit_scrape/Bohemia.txt",
  "damit_scrape/Bohlinia.txt",
  "damit_scrape/Bohrmann.txt",
  "damit_scrape/Bononia.txt",
  "damit_scrape/Borodino.txt",
  "damit_scrape/Brangane.txt",
  "damit_scrape/Brasilia.txt",
  "damit_scrape/Brel.txt",
  "damit_scrape/Britta.txt",
  "damit_scrape/Brouwer.txt",
  "damit_scrape/Brown.txt",
  "damit_scrape/Bruce.txt",
  "damit_scrape/Bruchsalia.txt",
  "damit_scrape/Bruna.txt",
  "damit_scrape/Buda.txt",
  "damit_scrape/Buzzi.txt",
  "damit_scrape/Byblis.txt",
  "damit_scrape/Caecilia.txt",
  "damit_scrape/Calvinia.txt",
  "damit_scrape/Camilla.txt",
  "damit_scrape/Camillo.txt",
  "damit_scrape/Campania.txt",
  "damit_scrape/Campanula.txt",
  "damit_scrape/Candy.txt",
  "damit_scrape/Carelia.txt",
  "damit_scrape/Carlova.txt",
  "damit_scrape/Cava.txt",
  "damit_scrape/Celuta.txt",
  "damit_scrape/Centesima.txt",
  "damit_scrape/Ceraskia.txt",
  "damit_scrape/Cerberus.txt",
  "damit_scrape/Cevenola.txt",
  "damit_scrape/Chaldaea.txt",
  "damit_scrape/Charlotte.txt",
  "damit_scrape/Chimay.txt",
  "damit_scrape/China.txt",
  "damit_scrape/Chloe.txt",
  "damit_scrape/Christine.txt",
  "damit_scrape/Cimbria.txt",
  "damit_scrape/Circe.txt",
  "damit_scrape/Clarissa.txt",
  "damit_scrape/Claudia.txt",
  "damit_scrape/Coelestina.txt",
  "damit_scrape/Colchis.txt",
  "damit_scrape/Columbia.txt",
  "damit_scrape/Comacina.txt",
  "damit_scrape/Concari.txt",
  "damit_scrape/Conrada.txt",
  "damit_scrape/Constantia.txt",
  "damit_scrape/Corduba.txt",
  "damit_scrape/Cosette.txt",
  "damit_scrape/Cosima.txt",
  "damit_scrape/Cremona.txt",
  "damit_scrape/Crescentia.txt",
  "damit_scrape/Crimea.txt",
  "damit_scrape/Cuitlahuac.txt",
  "damit_scrape/Cyane.txt",
  "damit_scrape/Cybele.txt",
  "damit_scrape/Danzig.txt",
  "damit_scrape/Daphne.txt",
  "damit_scrape/Datura.txt",
  "damit_scrape/David.txt",
  "damit_scrape/Davida.txt",
  "damit_scrape/Davidaguilar.txt",
  "damit_scrape/Dawn.txt",
  "damit_scrape/Deira.txt",
  "damit_scrape/Dejanira.txt",
  "damit_scrape/Dejopeja.txt",
  "damit_scrape/Dembowska.txt",
  "damit_scrape/Desagneauxa.txt",
  "damit_scrape/Di.txt",
  "damit_scrape/Dike.txt",
  "damit_scrape/Diotima.txt",
  "damit_scrape/Dirikis.txt",
  "damit_scrape/Dobrovolsky.txt",
  "damit_scrape/Dodona.txt",
  "damit_scrape/Doris.txt",
  "damit_scrape/Drakonia.txt",
  "damit_scrape/Dresda.txt",
  "damit_scrape/Druzhba.txt",
  "damit_scrape/Ducrosa.txt",
  "damit_scrape/Ducuroir.txt",
  "damit_scrape/Dudu.txt",
  "damit_scrape/Dysona.txt",
  "damit_scrape/Dyukov.txt",
  "damit_scrape/Dzhanibekov.txt",
  "damit_scrape/Echo.txt",
  "damit_scrape/Eckert.txt",
  "damit_scrape/Edburga.txt",
  "damit_scrape/Edisona.txt",
  "damit_scrape/Eduarda.txt",
  "damit_scrape/Eger.txt",
  "damit_scrape/Egeria.txt",
  "damit_scrape/Einhardress.txt",
  "damit_scrape/Einstein.txt",
  "damit_scrape/Ekard.txt",
  "damit_scrape/Elektra.txt",
  "damit_scrape/Eleonora.txt",
  "damit_scrape/Eleutheria.txt",
  "damit_scrape/Ella.txt",
  "damit_scrape/Elly.txt",
  "damit_scrape/Elsa.txt",
  "damit_scrape/Elvira.txt",
  "damit_scrape/Emma.txt",
  "damit_scrape/Epyaxa.txt",
  "damit_scrape/Erato.txt",
  "damit_scrape/Eric.txt",
  "damit_scrape/Erida.txt",
  "damit_scrape/Erigone.txt",
  "damit_scrape/Erika.txt",
  "damit_scrape/Erna.txt",
  "damit_scrape/Ernestina.txt",
  "damit_scrape/Eryan.txt",
  "damit_scrape/Erynia.txt",
  "damit_scrape/Esther.txt",
  "damit_scrape/Ethiopia.txt",
  "damit_scrape/Euboea.txt",
  "damit_scrape/Eugenia.txt",
  "damit_scrape/Eukrate.txt",
  "damit_scrape/Eulalia.txt",
  "damit_scrape/Euler.txt",
  "damit_scrape/Eunomia.txt",
  "damit_scrape/Euphrosyne.txt",
  "damit_scrape/Europa.txt",
  "damit_scrape/Eurynome.txt",
  "damit_scrape/Euterpe.txt",
  "damit_scrape/Eva.txt",
  "damit_scrape/Evgalvasil'ev.txt",
  "damit_scrape/Fanale.txt",
  "damit_scrape/Fanynka.txt",
  "damit_scrape/Feronia.txt",
  "damit_scrape/Fides.txt",
  "damit_scrape/Flammario.txt",
  "damit_scrape/Flora.txt",
  "damit_scrape/Florentina.txt",
  "damit_scrape/Fortuna.txt",
  "damit_scrape/Franklin-Adams.txt",
  "damit_scrape/Franziska.txt",
  "damit_scrape/Freia.txt",
  "damit_scrape/Fricke.txt",
  "damit_scrape/Fujiwara.txt",
  "damit_scrape/Fukuhara.txt",
  "damit_scrape/Gabriella.txt",
  "damit_scrape/Gaby.txt",
  "damit_scrape/Gagarin.txt",
  "damit_scrape/Gajdariya.txt",
  "damit_scrape/Galbraith.txt",
  "damit_scrape/Galene.txt",
  "damit_scrape/Galiani.txt",
  "damit_scrape/Galinskij.txt",
  "damit_scrape/Gallaj.txt",
  "damit_scrape/Ganymed.txt",
  "damit_scrape/Garumna.txt",
  "damit_scrape/Gaspra.txt",
  "damit_scrape/Geographos.txt",
  "damit_scrape/Geometria.txt",
  "damit_scrape/Gerda.txt",
  "damit_scrape/Gersuind.txt",
  "damit_scrape/Gerti.txt",
  "damit_scrape/Gezelle.txt",
  "damit_scrape/Gisela.txt",
  "damit_scrape/Glarona.txt",
  "damit_scrape/Glasenappia.txt",
  "damit_scrape/Godart.txt",
  "damit_scrape/Gorgo.txt",
  "damit_scrape/Gothlandia.txt",
  "damit_scrape/Gretia.txt",
  "damit_scrape/Griffin.txt",
  "damit_scrape/Gryphon.txt",
  "damit_scrape/Guinevere.txt",
  "damit_scrape/Hagar.txt",
  "damit_scrape/Hakone.txt",
  "damit_scrape/Halawe.txt",
  "damit_scrape/Hansa.txt",
  "damit_scrape/Happelia.txt",
  "damit_scrape/Harmonia.txt",
  "damit_scrape/Hebe.txt",
  "damit_scrape/Hedera.txt",
  "damit_scrape/Hektor.txt",
  "damit_scrape/Hela.txt",
  "damit_scrape/Helina.txt",
  "damit_scrape/Helsinki.txt",
  "damit_scrape/Hera.txt",
  "damit_scrape/Herculina.txt",
  "damit_scrape/Hermia.txt",
  "damit_scrape/Hermione.txt",
  "damit_scrape/Hermod.txt",
  "damit_scrape/Hertha.txt",
  "damit_scrape/Hesperia.txt",
  "damit_scrape/Heyuan.txt",
  "damit_scrape/Hidalgo.txt",
  "damit_scrape/Hilaritas.txt",
  "damit_scrape/Hildegard.txt",
  "damit_scrape/Hildrun.txt",
  "damit_scrape/Hippodamia.txt",
  "damit_scrape/Hirosetamotsu.txt",
  "damit_scrape/Hirundo.txt",
  "damit_scrape/Hocking.txt",
  "damit_scrape/Holda.txt",
  "damit_scrape/Holmberg.txt",
  "damit_scrape/Holmia.txt",
  "damit_scrape/Hopmann.txt",
  "damit_scrape/Huberta.txt",
  "damit_scrape/Hudson.txt",
  "damit_scrape/Humboldt.txt",
  "damit_scrape/Hungaria.txt",
  "damit_scrape/Hus.txt",
  "damit_scrape/Hygiea.txt",
  "damit_scrape/ITA.txt",
  "damit_scrape/Ianthe.txt",
  "damit_scrape/Ida.txt",
  "damit_scrape/Iduna.txt",
  "damit_scrape/Ikeya.txt",
  "damit_scrape/Ilse.txt",
  "damit_scrape/Ilsewa.txt",
  "damit_scrape/Impala.txt",
  "damit_scrape/Industria.txt",
  "damit_scrape/Ingeborg.txt",
  "damit_scrape/Io.txt",
  "damit_scrape/Iolanda.txt",
  "damit_scrape/Iphigenia.txt",
  "damit_scrape/Irene.txt",
  "damit_scrape/Iris.txt",
  "damit_scrape/Isabella.txt",
  "damit_scrape/Isara.txt",
  "damit_scrape/Ishihara.txt",
  "damit_scrape/Isis.txt",
  "damit_scrape/Istria.txt",
  "damit_scrape/Itha.txt",
  "damit_scrape/Iva.txt",
  "damit_scrape/Ivanka.txt",
  "damit_scrape/Ivar.txt",
  "damit_scrape/Izsak.txt",
  "damit_scrape/Jablunka.txt",
  "damit_scrape/Jacliff.txt",
  "damit_scrape/Jacqueline.txt",
  "damit_scrape/Jansje.txt",
  "damit_scrape/Jaroslawa.txt",
  "damit_scrape/Javid.txt",
  "damit_scrape/Jeanne.txt",
  "damit_scrape/Jena.txt",
  "damit_scrape/Jens.txt",
  "damit_scrape/Jetta.txt",
  "damit_scrape/Jiangxi.txt",
  "damit_scrape/Jimmysimms.txt",
  "damit_scrape/Johanmohr.txt",
  "damit_scrape/Johanna.txt",
  "damit_scrape/Joneberhart.txt",
  "damit_scrape/Jose.txt",
  "damit_scrape/Jugurtha.txt",
  "damit_scrape/Julia.txt",
  "damit_scrape/Juliana.txt",
  "damit_scrape/Juno.txt",
  "damit_scrape/Juzoitami.txt",
  "damit_scrape/Jyvaskyla.txt",
  "damit_scrape/Kaendler.txt",
  "damit_scrape/Kaho.txt",
  "damit_scrape/Kalbaugh.txt",
  "damit_scrape/Kalliope.txt",
  "damit_scrape/Kamegamori.txt",
  "damit_scrape/Kani.txt",
  "damit_scrape/Kaplan.txt",
  "damit_scrape/Karel.txt",
  "damit_scrape/Kariba.txt",
  "damit_scrape/Karin.txt",
  "damit_scrape/Karttunen.txt",
  "damit_scrape/Kate.txt",
  "damit_scrape/Katyusha.txt",
  "damit_scrape/Kemi.txt",
  "damit_scrape/Kenya.txt",
  "damit_scrape/Kitty.txt",
  "damit_scrape/Kiyosato.txt",
  "damit_scrape/Klare.txt",
  "damit_scrape/Klein.txt",
  "damit_scrape/Klemola.txt",
  "damit_scrape/Klotho.txt",
  "damit_scrape/Klumpkea.txt",
  "damit_scrape/Klymene.txt",
  "damit_scrape/Klytaemnestra.txt",
  "damit_scrape/Klytia.txt",
  "damit_scrape/Kondakov.txt",
  "damit_scrape/Korolev.txt",
  "damit_scrape/Koronis.txt",
  "damit_scrape/Kovacia.txt",
  "damit_scrape/Kressmannia.txt",
  "damit_scrape/Kriemhild.txt",
  "damit_scrape/Kristensen.txt",
  "damit_scrape/Kulikov.txt",
  "damit_scrape/Kundry.txt",
  "damit_scrape/Kunigunde.txt",
  "damit_scrape/Kuopio.txt",
  "damit_scrape/Kuritariku.txt",
  "damit_scrape/Kurohone.txt",
  "damit_scrape/Kustaanheimo.txt",
  "damit_scrape/Kylebardwell.txt",
  "damit_scrape/Kypria.txt",
  "damit_scrape/Lacadiera.txt",
  "damit_scrape/Lachesis.txt",
  "damit_scrape/Lacrimosa.txt",
  "damit_scrape/Laetitia.txt",
  "damit_scrape/Lamberta.txt",
  "damit_scrape/Landi.txt",
  "damit_scrape/Lanzia.txt",
  "damit_scrape/Laputa.txt",
  "damit_scrape/Latona.txt",
  "damit_scrape/Laugier.txt",
  "damit_scrape/Laurentia.txt",
  "damit_scrape/Lavonne.txt",
  "damit_scrape/Leda.txt",
  "damit_scrape/Lena.txt",
  "damit_scrape/Leonce.txt",
  "damit_scrape/Leontina.txt",
  "damit_scrape/Leto.txt",
  "damit_scrape/Leukothea.txt",
  "damit_scrape/Leverrier.txt",
  "damit_scrape/Libera.txt",
  "damit_scrape/Liberatrix.txt",
  "damit_scrape/Liberia.txt",
  "damit_scrape/Libussa.txt",
  "damit_scrape/Lilliana.txt",
  "damit_scrape/Limpopo.txt",
  "damit_scrape/Lindelof.txt",
  "damit_scrape/Lindstrom.txt",
  "damit_scrape/Liszt.txt",
  "damit_scrape/Lobachevskij.txt",
  "damit_scrape/Lohmann.txt",
  "damit_scrape/Lomia.txt",
  "damit_scrape/Lomonosowa.txt",
  "damit_scrape/Loreley.txt",
  "damit_scrape/Lucia.txt",
  "damit_scrape/Lucienne.txt",
  "damit_scrape/Lucifer.txt",
  "damit_scrape/Lucina.txt",
  "damit_scrape/Lucretia.txt",
  "damit_scrape/Ludmilla.txt",
  "damit_scrape/Luigimartella.txt",
  "damit_scrape/Lundmarka.txt",
  "damit_scrape/Lupo.txt",
  "damit_scrape/Lutetia.txt",
  "damit_scrape/Luxembourg.txt",
  "damit_scrape/Lydia.txt",
  "damit_scrape/Maartje.txt",
  "damit_scrape/Magnitka.txt",
  "damit_scrape/Magnya.txt",
  "damit_scrape/Maja.txt",
  "damit_scrape/Majella.txt",
  "damit_scrape/Malmquista.txt",
  "damit_scrape/Malzovia.txt",
  "damit_scrape/Mancunia.txt",
  "damit_scrape/Manfro.txt",
  "damit_scrape/Manto.txt",
  "damit_scrape/Manzano.txt",
  "damit_scrape/Marbachia.txt",
  "damit_scrape/Marceline.txt",
  "damit_scrape/Marconia.txt",
  "damit_scrape/Margarita.txt",
  "damit_scrape/Margo.txt",
  "damit_scrape/Marilyn.txt",
  "damit_scrape/Marlene.txt",
  "damit_scrape/Marlu.txt",
  "damit_scrape/Masaryk.txt",
  "damit_scrape/Massalia.txt",
  "damit_scrape/Mathieu.txt",
  "damit_scrape/Maupertuis.txt",
  "damit_scrape/Mavis.txt",
  "damit_scrape/Mechthild.txt",
  "damit_scrape/Medea.txt",
  "damit_scrape/Medusa.txt",
  "damit_scrape/Melete.txt",
  "damit_scrape/Melpomene.txt",
  "damit_scrape/Menippe.txt",
  "damit_scrape/Mertona.txt",
  "damit_scrape/Merxia.txt",
  "damit_scrape/Messina.txt",
  "damit_scrape/Meta.txt",
  "damit_scrape/Metcalfia.txt",
  "damit_scrape/Metis.txt",
  "damit_scrape/Mieke.txt",
  "damit_scrape/Milet.txt",
  "damit_scrape/Millis.txt",
  "damit_scrape/Mimi.txt",
  "damit_scrape/Minerva.txt",
  "damit_scrape/Mitaka.txt",
  "damit_scrape/Miyazaki.txt",
  "damit_scrape/Miyazawakenji.txt",
  "damit_scrape/Mohler.txt",
  "damit_scrape/Molchan.txt",
  "damit_scrape/Mongmanwai.txt",
  "damit_scrape/Montana.txt",
  "damit_scrape/Morbidelli.txt",
  "damit_scrape/Moskva.txt",
  "damit_scrape/Muonio.txt",
  "damit_scrape/Musa.txt",
  "damit_scrape/Myroncope.txt",
  "damit_scrape/Myrrha.txt",
  "damit_scrape/Naantali.txt",
  "damit_scrape/Naef.txt",
  "damit_scrape/Nasi.txt",
  "damit_scrape/Nassovia.txt",
  "damit_scrape/Natascha.txt",
  "damit_scrape/Nausikaa.txt",
  "damit_scrape/Ndola.txt",
  "damit_scrape/Neckar.txt",
  "damit_scrape/Nele.txt",
  "damit_scrape/Nemausa.txt",
  "damit_scrape/Nephthys.txt",
  "damit_scrape/Nerthus.txt",
  "damit_scrape/Niobe.txt",
  "damit_scrape/Noether.txt",
  "damit_scrape/Nonie.txt",
  "damit_scrape/Noviomagum.txt",
  "damit_scrape/Nriag.txt",
  "damit_scrape/Numerowia.txt",
  "damit_scrape/Numidia.txt",
  "damit_scrape/Nuwa.txt",
  "damit_scrape/Nymphe.txt",
  "damit_scrape/Nysa.txt",
  "damit_scrape/Nyx.txt",
  "damit_scrape/Oberkochen.txt",
  "damit_scrape/Odessa.txt",
  "damit_scrape/Ohre.txt",
  "damit_scrape/Olbersia.txt",
  "damit_scrape/Olympiada.txt",
  "damit_scrape/Onnie.txt",
  "damit_scrape/Ookuninushi.txt",
  "damit_scrape/Oort.txt",
  "damit_scrape/Oosterhoff.txt",
  "damit_scrape/Ophelia.txt",
  "damit_scrape/Orchis.txt",
  "damit_scrape/Ornamenta.txt",
  "damit_scrape/Osita.txt",
  "damit_scrape/Ostara.txt",
  "damit_scrape/Ostenia.txt",
  "damit_scrape/Otero.txt",
  "damit_scrape/Ottegebe.txt",
  "damit_scrape/Otthild.txt",
  "damit_scrape/Otto.txt",
  "damit_scrape/Paeonia.txt",
  "damit_scrape/Pakhmutova.txt",
  "damit_scrape/Pallas.txt",
  "damit_scrape/Palma.txt",
  "damit_scrape/Palomaa.txt",
  "damit_scrape/Pandora.txt",
  "damit_scrape/Papagena.txt",
  "damit_scrape/Paradise.txt",
  "damit_scrape/Parthenope.txt",
  "damit_scrape/Patrice.txt",
  "damit_scrape/Patricia.txt",
  "damit_scrape/Paulina.txt",
  "damit_scrape/Pauly.txt",
  "damit_scrape/Pax.txt",
  "damit_scrape/Penelope.txt",
  "damit_scrape/Penthesilea.txt",
  "damit_scrape/Pepita.txt",
  "damit_scrape/Persephone.txt",
  "damit_scrape/Peter.txt",
  "damit_scrape/Petofi.txt",
  "damit_scrape/Petra-Pepi.txt",
  "damit_scrape/Petrina.txt",
  "damit_scrape/Petropolitana.txt",
  "damit_scrape/Petunia.txt",
  "damit_scrape/Pfund.txt",
  "damit_scrape/Phaedra.txt",
  "damit_scrape/Phaetusa.txt",
  "damit_scrape/Philagoria.txt",
  "damit_scrape/Philippina.txt",
  "damit_scrape/Philomela.txt",
  "damit_scrape/Phocaea.txt",
  "damit_scrape/Phryne.txt",
  "damit_scrape/Phthia.txt",
  "damit_scrape/Phyllis.txt",
  "damit_scrape/Pia.txt",
  "damit_scrape/Piccolo.txt",
  "damit_scrape/Picka.txt",
  "damit_scrape/Pickeringia.txt",
  "damit_scrape/Pierretta.txt",
  "damit_scrape/Pirola.txt",
  "damit_scrape/Pittsburghia.txt",
  "damit_scrape/Polyxena.txt",
  "damit_scrape/Pomona.txt",
  "damit_scrape/Portlandia.txt",
  "damit_scrape/Posnania.txt",
  "damit_scrape/Postrema.txt",
  "damit_scrape/Povenmire.txt",
  "damit_scrape/Prisma.txt",
  "damit_scrape/Proserpina.txt",
  "damit_scrape/Protogeneia.txt",
  "damit_scrape/Prudentia.txt",
  "damit_scrape/Psyche.txt",
  "damit_scrape/Pulcova.txt",
  "damit_scrape/Punkaharju.txt",
  "damit_scrape/Pyrrha.txt",
  "damit_scrape/Ra-Shalom.txt",
  "damit_scrape/Radegast.txt",
  "damit_scrape/Raimonda.txt",
  "damit_scrape/Raissa.txt",
  "damit_scrape/Raphaela.txt",
  "damit_scrape/Rarahu.txt",
  "damit_scrape/Rebekka.txt",
  "damit_scrape/Recha.txt",
  "damit_scrape/Reinmuthia.txt",
  "damit_scrape/Reni.txt",
  "damit_scrape/Renzia.txt",
  "damit_scrape/Reseda.txt",
  "damit_scrape/Rezia.txt",
  "damit_scrape/Rhodope.txt",
  "damit_scrape/Riceia.txt",
  "damit_scrape/Rickfienberg.txt",
  "damit_scrape/Ricouxa.txt",
  "damit_scrape/Roberts.txt",
  "damit_scrape/Roehla.txt",
  "damit_scrape/Rogeria.txt",
  "damit_scrape/Rohloff.txt",
  "damit_scrape/Rosalinde.txt",
  "damit_scrape/Rosamunde.txt",
  "damit_scrape/Rosselia.txt",
  "damit_scrape/Rotraut.txt",
  "damit_scrape/Rovaniemi.txt",
  "damit_scrape/Roxane.txt",
  "damit_scrape/Royer.txt",
  "damit_scrape/Runcorn.txt",
  "damit_scrape/Ruperto-Carola.txt",
  "damit_scrape/Ruth.txt",
  "damit_scrape/Rutherfordia.txt",
  "damit_scrape/Sabine.txt",
  "damit_scrape/Sagan.txt",
  "damit_scrape/Saheki.txt",
  "damit_scrape/Salli.txt",
  "damit_scrape/Salome.txt",
  "damit_scrape/Salonta.txt",
  "damit_scrape/Salvia.txt",
  "damit_scrape/Sanenobufukui.txt",
  "damit_scrape/Sanpoloamosciano.txt",
  "damit_scrape/Sappho.txt",
  "damit_scrape/Sarema.txt",
  "damit_scrape/Savo.txt",
  "damit_scrape/Schaifers.txt",
  "damit_scrape/Scheila.txt",
  "damit_scrape/Schmidt.txt",
  "damit_scrape/Schulhof.txt",
  "damit_scrape/Scylla.txt",
  "damit_scrape/Sebastiana.txt",
  "damit_scrape/Sedov.txt",
  "damit_scrape/Segovia.txt",
  "damit_scrape/Seinajoki.txt",
  "damit_scrape/Semiramis.txt",
  "damit_scrape/Senta.txt",
  "damit_scrape/Sequoia.txt",
  "damit_scrape/Shajna.txt",
  "damit_scrape/Shandong.txt",
  "damit_scrape/Shaposhnikov.txt",
  "damit_scrape/Shenzhen.txt",
  "damit_scrape/Shmakova.txt",
  "damit_scrape/Siegena.txt",
  "damit_scrape/Sigrid.txt",
  "damit_scrape/Sigune.txt",
  "damit_scrape/Silesia.txt",
  "damit_scrape/Silke.txt",
  "damit_scrape/Sillanpaa.txt",
  "damit_scrape/Silvretta.txt",
  "damit_scrape/Sirona.txt",
  "damit_scrape/Skuld.txt",
  "damit_scrape/Smithsonian.txt",
  "damit_scrape/Sobolev.txt",
  "damit_scrape/Solon.txt",
  "damit_scrape/Solov'yanenko.txt",
  "damit_scrape/Somalia.txt",
  "damit_scrape/Somnium.txt",
  "damit_scrape/Somville.txt",
  "damit_scrape/Sorga.txt",
  "damit_scrape/Sormano.txt",
  "damit_scrape/Stanislav.txt",
  "damit_scrape/Stavropolis.txt",
  "damit_scrape/Stephania.txt",
  "damit_scrape/Steverin.txt",
  "damit_scrape/Storeria.txt",
  "damit_scrape/Suevia.txt",
  "damit_scrape/Sundmania.txt",
  "damit_scrape/Suvanto.txt",
  "damit_scrape/Suzuki.txt",
  "damit_scrape/Svejk.txt",
  "damit_scrape/Sylvania.txt",
  "damit_scrape/Sylvia.txt",
  "damit_scrape/Tacitus.txt",
  "damit_scrape/Tama.txt",
  "damit_scrape/Tammydickinson.txt",
  "damit_scrape/Tanina.txt",
  "damit_scrape/Tarka.txt",
  "damit_scrape/Tarry.txt",
  "damit_scrape/Tatjana.txt",
  "damit_scrape/Tatsuo.txt",
  "damit_scrape/Taurinensis.txt",
  "damit_scrape/Teller.txt",
  "damit_scrape/Tercidina.txt",
  "damit_scrape/Tezcatlipoca.txt",
  "damit_scrape/Thalia.txt",
  "damit_scrape/Thekla.txt",
  "damit_scrape/Themis.txt",
  "damit_scrape/Theodora.txt",
  "damit_scrape/Thernoe.txt",
  "damit_scrape/Thetis.txt",
  "damit_scrape/Thisbe.txt",
  "damit_scrape/Thomana.txt",
  "damit_scrape/Thomsen.txt",
  "damit_scrape/Thuringia.txt",
  "damit_scrape/Thyra.txt",
  "damit_scrape/Tiflis.txt",
  "damit_scrape/Tinchen.txt",
  "damit_scrape/Tinette.txt",
  "damit_scrape/Tirela.txt",
  "damit_scrape/Titicaca.txt",
  "damit_scrape/Tjilaki.txt",
  "damit_scrape/Tolosa.txt",
  "damit_scrape/Tomoegozen.txt",
  "damit_scrape/Tomyris.txt",
  "damit_scrape/Tonyspear.txt",
  "damit_scrape/Trebon.txt",
  "damit_scrape/Turku.txt",
  "damit_scrape/Tvardovskij.txt",
  "damit_scrape/Tyche.txt",
  "damit_scrape/Ueta.txt",
  "damit_scrape/Ukraina.txt",
  "damit_scrape/Ulrike.txt",
  "damit_scrape/Ulula.txt",
  "damit_scrape/Ulyanov.txt",
  "damit_scrape/Una.txt",
  "damit_scrape/Unitas.txt",
  "damit_scrape/United.txt",
  "damit_scrape/Univsima.txt",
  "damit_scrape/Urania.txt",
  "damit_scrape/Urata.txt",
  "damit_scrape/Urda.txt",
  "damit_scrape/Ursa.txt",
  "damit_scrape/Valdivia.txt",
  "damit_scrape/Valsecchi.txt",
  "damit_scrape/Varsavia.txt",
  "damit_scrape/Vassar.txt",
  "damit_scrape/Vaticana.txt",
  "damit_scrape/Venusia.txt",
  "damit_scrape/Vera.txt",
  "damit_scrape/Veritas.txt",
  "damit_scrape/Verne.txt",
  "damit_scrape/Verolacqua.txt",
  "damit_scrape/Vibilia.txt",
  "damit_scrape/Victoria.txt",
  "damit_scrape/Villigera.txt",
  "damit_scrape/Virtanen.txt",
  "damit_scrape/Vitginzburg.txt",
  "damit_scrape/Vivian.txt",
  "damit_scrape/Vojno-Yasenetsky.txt",
  "damit_scrape/Vulkaneifel.txt",
  "damit_scrape/Vyssotsky.txt",
  "damit_scrape/Wachmann.txt",
  "damit_scrape/Wakkanai.txt",
  "damit_scrape/Walkure.txt",
  "damit_scrape/Walraven.txt",
  "damit_scrape/Wawel.txt",
  "damit_scrape/Weisell.txt",
  "damit_scrape/Wempe.txt",
  "damit_scrape/Werdandi.txt",
  "damit_scrape/Weringia.txt",
  "damit_scrape/Wesselink.txt",
  "damit_scrape/Winchester.txt",
  "damit_scrape/Wladilena.txt",
  "damit_scrape/Wratislavia.txt",
  "damit_scrape/Wright.txt",
  "damit_scrape/Wurm.txt",
  "damit_scrape/Xenia.txt",
  "damit_scrape/Xenophanes.txt",
  "damit_scrape/Yamada.txt",
  "damit_scrape/Yeungchuchiu.txt",
  "damit_scrape/Yrsa.txt",
  "damit_scrape/Yugoslavia.txt",
  "damit_scrape/Yurilvovia.txt",
  "damit_scrape/Yvonne.txt",
  "damit_scrape/Zerlina.txt",
  "damit_scrape/Zita.txt",
  "damit_scrape/Zoya.txt",
  "other/bennu.txt"
];
